title: Le Sphérier
author: fhiegel
twitter_username: de-dale
github_username: de-dale
slack: de-dale
rss: rss

theme: minima

header_pages:
 - index.md
 - cards.md

# Exclude from processing.
exclude:
 - Gemfile
 - Gemfile.lock
 - vendor
 - main
 - node_modules
 - scripts
 - src
 - webpack